version: '3.8'

services:
  node:
    container_name: app
    build: docker/node
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - ${NODE_PORT}:3000
    command: npm run start:dev

  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432